# Generated by Django 3.2.4 on 2021-06-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210614_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
