# Generated by Django 3.2.4 on 2021-06-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210614_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsellerprofile',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Seller Profile'},
        ),
        migrations.AlterModelOptions(
            name='sellerprofile',
            options={'verbose_name': 'Seller Profile', 'verbose_name_plural': 'Seller Profiles'},
        ),
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
    ]
