# Generated by Django 3.2.4 on 2021-06-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210616_1316'),
        ('accounts', '0004_auto_20210616_1152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalSellerProfile',
            new_name='HistoricalSeller',
        ),
        migrations.RenameModel(
            old_name='SellerProfile',
            new_name='Seller',
        ),
        migrations.AlterModelOptions(
            name='historicalseller',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Seller'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Seller', 'verbose_name_plural': 'Sellers'},
        ),
    ]
