# Generated by Django 3.2.4 on 2021-06-18 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_historicalproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='percent',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Coupon Percentage'),
        ),
    ]
