# Generated by Django 3.2.4 on 2021-06-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210618_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
    ]
