# Generated by Django 3.2.4 on 2021-06-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Price'),
        ),
    ]
